pipeline {
    agent any
    stages {
        stage('Tools initialization') {
            steps {
                echo 'Installing dependencies'
                sh 'go version'
                sh 'go get -u golang.org/x/lint/golint'
            }
        }

        stage("Checkout Code") {
            steps {
                echo 'Getting code'
                git branch: 'master',
                        url: 'https://github.com/filib1234/gojenkins'
            }
        }

        stage('Build') {
            steps {
                echo 'Compiling and building'
                sh 'go build'
            }
        }

        stage('code analysis') {
            steps {
                    echo 'Running vetting'
                    sh 'go vet .'
                    echo 'Running linting'
                    sh 'golint .'
            }
        }

        stage('Test') {
            steps {
                echo 'Running test'
                sh 'go test'
            }
        }

    }
    post {
        always {
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                    recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                    to: "${params.RECIPIENTS}",
                    subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"

        }
    }
}
