@Library('pipeline-library') _

import com.filip.GlobalVars
import com.filip.SampleClass

pipeline {
    agent any
    stages {
        stage('normal echo') {
            steps {
                echo 'Hello, world'
                sayHello 'Dave'

                echo 'The value of foo is : ' + GlobalVars.foo

                script {
                    def person = new SampleClass()
                    person.age = 21
                    person.increaseAge(10)
                    echo 'Incremented age, is now : ' + person.age
                }
            }
        }
    }
}
