@Library('pipeline-library') _

import com.filip.GlobalVars
import com.filip.SampleClass

pipeline {
    agent any
    stages {
        stage('say hello') {
            steps {
                echo 'Hello, world'
            }
        }
        stage('echo from sharedLibs') {
            steps {
                sayHello ${NAME}
            }
        }
        stage('echo from global var') {
             steps {
                 echo 'The value of foo is : ' + GlobalVars.foo
             }
        }
        stage('echo from shared object') {
             steps {
                script {
                   def person = new SampleClass()
                   person.age = 21
                   echo 'Person age is : ' + person.age
                   def inc = 10
                   echo 'Increasing by : ' + inc
                   person.increaseAge(inc)
                   echo 'Incremented age, is now : ' + person.age
                }
             }
        }
        stage('say bye bye') {
            steps {
                sayByeBye ${NAME}
            }
        }
    }
}
