@Library('pipeline-library') _
javaWithMaven 'https://github.com/iamvickyav/spring-boot-data-H2-embedded.git'

pipeline {
    agent any
    stages {
        stage('say hello') {
            steps {
                echo 'Hello, world'
            }
        }
    }
}
