@Library('pipeline-library') _

pipeline {
    agent any
    stages {
        javaWithMaven 'https://github.com/iamvickyav/spring-boot-data-H2-embedded.git'
        stage('say hello') {
            steps {
                echo 'Hello, world'
            }
        }
    }
}
